# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_stay_out_late', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passresults',
            name='passdttime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
