# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_stay_out_late', '0003_auto_20170525_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretime', models.DateTimeField(auto_now=True)),
                ('carecontent', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explaintime', models.DateTimeField(auto_now=True)),
                ('explaimcontent', models.CharField(blank=True, max_length=100, null=True)),
                ('ifagree', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='passresults',
            name='lastpasstime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passresults',
            name='care',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_stay_out_late.Care'),
        ),
        migrations.AddField(
            model_name='passresults',
            name='explain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_stay_out_late.Explain'),
        ),
    ]
